### ISSUE TITLE
Line numbers are always 1

### ISSUE THREAD

**Issue by benkasminbullock** [dgl/cpangrep#45] opened 2015-11-06 01:48 UTC
The line numbers always come out as 1:

http://grep.cpan.me/?q=nice%2C+rice%2C+lice
https://metacpan.org/source/BKB/Text-Fuzzy-0.22/examples/list-context.pl#L1

http://grep.cpan.me/?q=Gotta+get+down+on+Friday
https://metacpan.org/source/BKB/JSON-Parse-0.38/lib/JSON/Parse.pod#L1

Every other example I have tried gives a line number of 1.

The line number seems to be printed here:

https://github.com/dgl/cpangrep/blob/4fc4f0fdacce8a2edc5ee519ad53c0762b82315f/lib/WWW/CPANGrep.pm#L169

using a value which is set here:

https://github.com/dgl/cpangrep/blob/4fc4f0fdacce8a2edc5ee519ad53c0762b82315f/lib/WWW/CPANGrep/Matcher.pm#L170

from calculations here:

https://github.com/dgl/cpangrep/blob/4fc4f0fdacce8a2edc5ee519ad53c0762b82315f/lib/WWW/CPANGrep/Matcher.pm#L162

Without running the code I cannot see what's wrong in the above, but it is always coming out as 1.

By the way, thanks for the useful grep.cpan.me service.

**Comment by tsibley** [comment] 2015-11-06 01:52
I can't reproduce this clicking the links above, nor with the App::cpangrep command line client, which uses the web API.

**Comment by tsibley** [comment] 2015-11-06 01:53
If you look at the HTML of a results page that's got the wrong line numbers, what do you see?

**Comment by tsibley** [comment] 2015-11-06 01:55
Oooh, I think I know what's happening.  :-)  Click the code hunk, not the linked filename.

That is, you're clicking the link produced by: https://github.com/dgl/cpangrep/blob/4fc4f0fdacce8a2edc5ee519ad53c0762b82315f/lib/WWW/CPANGrep.pm#L174-L176

Not the link produced by: https://github.com/dgl/cpangrep/blob/4fc4f0fdacce8a2edc5ee519ad53c0762b82315f/lib/WWW/CPANGrep.pm#L169

**Comment by benkasminbullock** [comment] 2015-11-06 02:17
> Click the code hunk, not the linked filename.

I didn't even know there was a link on the code hunk. Maybe this is something of a web design/usability issue? Feel free to close this if you want to.

**Comment by tsibley** [comment] 2015-11-06 02:39
I agree it's not obvious the code hunks are links.  The only hint is that your pointer will change when you mouse over it.  I'm not a repo owner, I can't close it even if I wanted to.  Just an interested bystander.  :-)

**Comment by benkasminbullock** [comment] 2015-11-06 04:56
> I agree it's not obvious the code hunks are links. 

I wasn't expecting to find links there. My mental model of how search pages work is Google, and I don't get those links on Google, so it would help to have some visual guidance. It's also not obvious that they are going to the specific line numbers of the file.

The other usability problem is that the link to the file takes me to "#L1" of the file, which really doesn't make sense. If it's a link to the file in general, then there's no reason to link to line one of the file. That is just confusing.

Anyway now that I know how to use it better, I'll be able to work the system. It's up to the owner of the repository whether they want to worry about usability or not. If this doesn't help, feel free to delete.

**Comment by dgl** [comment] 2015-11-06 12:35
I just dropped the linking to line 1, maybe makes things clearer.

**Closed by dgl** 2015-11-06 12:35 UTC
